language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php
notifications:
  email:
    recipents: 
      - mstaehely@gmail.com
      - mstaehel@uw.edu
      - mstaehel@cs.washington.edu
    on_success: always
